pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    
    environment {
        cluster = "vproappProd"
        service = "vprofileapptask-service-prod"
    }

    stages {

        stage('Deploy to Prod ECS'){
            steps {
                withAWS(credentials: 'awscreds', region: 'eu-north-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        
    }
    }
}
