pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    
    environment {
        SNAP_REPO = 'vprofile-snapshot'
		NEXUS_USER = 'admin'
		NEXUS_PASS = '123456789'
		RELEASE_REPO = 'vprofile-release'
		CENTRAL_REPO = 'vpro-maven-central'
		NEXUSIP = '172.31.28.232'
		NEXUSPORT = '8081'
		NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SOVAERSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'
        registryCredentials = 'ecr:eu-north-1:awscreds'
        appRegistry = '800762439524.dkr.ecr.eu-north-1.amazonaws.com/vprofileappimg'
        vprofileRegistry = 'https://800762439524.dkr.ecr.eu-north-1.amazonaws.com'
        cluster = "vproappstaging"
        service = "vprofileapptask-service-qnjtgy3f"
    }

    stages {
        stage('Build'){
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
            post{
                success {
                    echo "Now Archiving."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Test'){
            steps {
                sh 'mvn -s settings.xml test'
            }
        }

        stage('Checkstyle Analysis'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }

        stage('Sonar Analysis') {
            environment {
                scannerHome = tool "${SONARSCANNER }"
            }
            steps{  
                withSonarQubeEnv("${SOVAERSERVER}"){
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile\
                    -Dsonar.projectName=vprofile \
                    -Dsonar.projectVersion=1.0 \
                    -Dsonar.sources=src/ \
                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                    -Dsonar.junit.reportsPath=target/surefire-reports/ \
                    -Dsonar.jacoco.reportsPaths=target/jacoco.exec \
                    -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }

        stage ('Quality Gate') {
			steps {
				timeout (time : 1, unit : 'HOURS') {
					waitForQualityGate abortPipeline :true
				}
			}
		}

        stage ('UploadArtifact') {
			steps {  
				nexusArtifactUploader (
					nexusVersion : 'nexus3',
					protocol : 'http',
					nexusUrl : "${NEXUSIP}:${NEXUSPORT}",
					groupId : "QA",
					version : "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
					repository : "${RELEASE_REPO}",
					credentialsId : "${NEXUS_LOGIN}",
					artifacts : [
						[
							artifactId : 'vproapp',
							classifier : '',
							file : 'target/vprofile-v2.war',
							type : 'war'
							
						]
					]
					
				)
			}
		}

        stage("Build App Image"){
            steps {
                script {
                    dockerImage = docker.build(appRegistry + ":$BUILD_NUMBER","./Docker-files/app/multistage/")
                }
            }
        }

        stage("Upload App Image"){
            steps {
                script {
                    docker.withRegistry(vprofileRegistry, registryCredentials) {
                        dockerImage.push("BUILD_NUMBER")
                        dockerImage.push("latest")
                }
            }
        }
    }

        stage('Deploy to Staging ECS'){
            steps {
                withAWS(credentials: 'awscreds', region: 'eu-north-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }


}
}
